import { constants, createPrivateKey, privateDecrypt } from "node:crypto";
import { Buffer } from "node:buffer";
const MAGIC=Buffer.from("workspace-cleanup-locator-v1\0","utf8");
function b64(value,label,min=1,max=4096){if(typeof value!=="string"||!value||value.length>max*2||!/^[A-Za-z0-9_-]+$/.test(value))throw new Error(label+" is invalid");const bytes=Buffer.from(value,"base64url");if(bytes.byteLength<min||bytes.byteLength>max||bytes.toString("base64url")!==value)throw new Error(label+" is invalid");return bytes;}
function branch(value,label){if(typeof value!=="string"||value.length<1||value.length>128||value.startsWith("/")||value.endsWith("/")||value.includes("..")||/[\x00-\x20~^:?*\[\\]/.test(value)||value.includes("@{"))throw new Error(label+" is invalid");return value;}
function sha(value){if(typeof value!=="string"||!(/^[0-9a-f]{40}$/i.test(value)||/^[0-9a-f]{64}$/i.test(value)))throw new Error("source_sha is invalid");return value.toLowerCase();}
function repositoryId(value){const n=Number(value);if(!Number.isSafeInteger(n)||n<1)throw new Error("repository_id is invalid");return n;}
export function openCleanupLocator(privateKeyPem,encoded){if(typeof privateKeyPem!=="string"||!privateKeyPem.includes("PRIVATE KEY"))throw new Error("cleanup unwrap key is unavailable");const clear=privateDecrypt({key:createPrivateKey(privateKeyPem),padding:constants.RSA_PKCS1_OAEP_PADDING,oaepHash:"sha256"},b64(encoded,"cleanup_capsule",256,1024));if(clear.byteLength<=MAGIC.byteLength||!clear.subarray(0,MAGIC.byteLength).equals(MAGIC))throw new Error("cleanup locator magic is invalid");let value;try{value=JSON.parse(clear.subarray(MAGIC.byteLength).toString("utf8"));}catch{throw new Error("cleanup locator payload is invalid");}if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("cleanup locator payload is invalid");const allowed=new Set(["v","repository_id","baseline_branch","source_branch","source_sha","dispatch_branch","keys_branch"]);for(const key of Object.keys(value))if(!allowed.has(key))throw new Error("cleanup locator contains unknown field");if(value.v!==1)throw new Error("cleanup locator version is unsupported");return Object.freeze({v:1,repository_id:repositoryId(value.repository_id),baseline_branch:branch(value.baseline_branch,"baseline_branch"),source_branch:branch(value.source_branch,"source_branch"),source_sha:sha(value.source_sha),dispatch_branch:branch(value.dispatch_branch,"dispatch_branch"),keys_branch:branch(value.keys_branch,"keys_branch")});}
export const CLEANUP_LOCATOR_MAGIC=MAGIC;
